version: '3.3'
services:
    jenkins-master:
        container_name: jenkins-master
        ports:
            - '8080:8080'
            - '50000:50000'
        image: jenkins-master
    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://192.168.1.102:8080'
        image: jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins-master
